version: '3'
name: simple-api
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: simple-server
    restart: always
    ports:
      - '${SERVER_PORT}:80'
    volumes:
      - ./:/var/www/html
    networks:
      - simple-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: simple-db
    environment: 
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - simple-volume:/var/lib/mysql
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - ${MYSQL_PORT}:3306
    networks:
      - simple-network

volumes:
  simple-volume:
    driver: local
  vendor:

networks: 
  simple-network:
    driver: bridge
